version: '3.7'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: "no"
    links:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  bet_maker:
    build: ./bet_maker
    command: bash -c "uvicorn main:app --host 0.0.0.0 --reload --port 8002 --loop asyncio"
    env_file:
      - .env
    ports:
      - "8002:8002"
    depends_on:
      - zookeeper
      - kafka

  line_provider:
    build: ./line_provider
    command: bash -c "uvicorn main:app --host 0.0.0.0 --reload --port 8001"
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - zookeeper
      - kafka


volumes:
  postgres_data: