"""add status field

Revision ID: 1044aee5b5c6
Revises: 95c86bf8f1d7
Create Date: 2024-10-28 21:14:16.488342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1044aee5b5c6'
down_revision: Union[str, None] = '95c86bf8f1d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bets', 'status')
    # ### end Alembic commands ###
